"""
Import audit (Epic 3 of the spec): reads a persona folder that ALREADY
exists — generated by hand, by a generic `create-persona`, or imported
from another OpenClaw-like format — and proposes an `org.yaml` fragment
(role + actor) for a human to review before accepting it.

It deliberately does NOT write directly to any org.yaml: it is a
heuristic over free text (Markdown without guaranteed structure), so it
can be wrong. Every field that could not be inferred with confidence is
left as an explicit warning instead of being filled with an invented
value — see the "don't fill gaps with assumptions" principle we already
apply to the rest of PhantomOrg.
"""

from __future__ import annotations

import difflib
import re
from dataclasses import dataclass, field
from pathlib import Path

from ..spec.model import OrgSpec
from ..spec.shape_validator import is_valid_identifier, slugify_id

_TELEGRAM_BOT_RE = re.compile(r"@[\w]+_bot\b")
_ROLE_PATTERNS = [
    re.compile(r"\*\*Role\*\*:\s*(.+)"),
    re.compile(r"^#+\s*Role\s*:\s*(.+)$", re.MULTILINE),
    re.compile(r"\bRole:\s*(.+)", re.IGNORECASE),
]
_REPORTS_TO_PATTERNS = [
    re.compile(r"\*\*Reports to\*\*:\s*(.+)"),
    re.compile(r"\breports?\s*to\s*:\s*(.+)", re.IGNORECASE),
]
_DEPARTMENT_PATTERNS = [
    re.compile(r"\*\*Department\*\*:\s*(.+)"),
    re.compile(r"\bDepartment:\s*(.+)", re.IGNORECASE),
]
_TOOL_BULLET_RE = re.compile(r"^-\s+([A-Za-z0-9_./-]+)\s*$", re.MULTILINE)
_CANDIDATE_SPLIT_RE = re.compile(r",|\by\b|\bo\b|\bor\b|\band\b", re.IGNORECASE)

_FUZZY_CUTOFF = 0.8  # 0-1; higher = stricter. difflib.get_close_matches (stdlib).


@dataclass
class ImportFindings:
    actor_id: str
    telegram_bot: str | None = None
    role_name_guess: str | None = None
    reports_to_guess: str | None = None
    department_guess: str | None = None
    tools_guess: list[str] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)
    sources_read: list[str] = field(default_factory=list)


def audit_persona_dir(persona_dir: Path) -> ImportFindings:
    """
    Analyzes IDENTITY.md / SOUL.md / tools.md inside persona_dir (those
    that exist) and returns an ImportFindings with what was detected and
    an explicit warnings list for everything that could not be inferred.
    """
    persona_dir = Path(persona_dir)
    raw_name = persona_dir.name
    slug = slugify_id(raw_name)
    if slug and is_valid_identifier(slug) and slug != raw_name:
        actor_id = slug
    else:
        actor_id = raw_name
    findings = ImportFindings(actor_id=actor_id)
    if actor_id != raw_name:
        findings.warnings.append(
            f"Actor id normalized to {actor_id!r} from directory name "
            f"{raw_name!r} to satisfy the identifier grammar"
        )

    combined_text = ""
    for filename in ["IDENTITY.md", "SOUL.md", "tools.md"]:
        p = persona_dir / filename
        if p.exists():
            try:
                combined_text += p.read_text(encoding="utf-8") + "\n"
                findings.sources_read.append(filename)
            except (OSError, UnicodeDecodeError) as e:
                findings.warnings.append(
                    f"Could not read {filename}: {e}; the import may be incomplete"
                )
        else:
            findings.warnings.append(
                f"Could not find {filename}; the import may be incomplete"
            )

    if not combined_text.strip():
        findings.warnings.append(
            "Could not read any recognizable file in this folder "
            "(expected at least IDENTITY.md, SOUL.md or tools.md)"
        )
        return findings

    bot_match = _TELEGRAM_BOT_RE.search(combined_text)
    if bot_match:
        findings.telegram_bot = bot_match.group(0)
    else:
        findings.warnings.append("No Telegram bot handle detected (@..._bot)")

    role_name = None
    for pattern in _ROLE_PATTERNS:
        m = pattern.search(combined_text)
        if m:
            role_name = m.group(1).strip()
            break
    if role_name:
        findings.role_name_guess = role_name
    else:
        findings.warnings.append(
            "No explicit role detected ('**Role**:' or similar); "
            "it will have to be assigned by hand with --role-id"
        )

    reports_to = None
    for pattern in _REPORTS_TO_PATTERNS:
        m = pattern.search(combined_text)
        if m:
            reports_to = m.group(1).strip()
            break
    if reports_to:
        findings.reports_to_guess = reports_to
    else:
        findings.warnings.append(
            "Could not detect who this actor reports to; review "
            "reports_to/reports_to_human by hand"
        )

    department_name = None
    for pattern in _DEPARTMENT_PATTERNS:
        m = pattern.search(combined_text)
        if m:
            department_name = m.group(1).strip()
            break
    if department_name:
        findings.department_guess = department_name
    else:
        findings.warnings.append(
            "No explicit department detected ('**Department**:' or "
            "similar); if --against-org can't infer it either, it will "
            "have to be passed by hand with --department"
        )

    tools_path = persona_dir / "tools.md"
    if tools_path.exists():
        try:
            tools_text = tools_path.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError) as e:
            findings.warnings.append(
                f"Could not read tools.md: {e}; tool list left empty"
            )
            tools_text = ""
        tool_lines = _TOOL_BULLET_RE.findall(tools_text)
        findings.tools_guess = tool_lines
        if not tool_lines:
            findings.warnings.append(
                "tools.md exists but no tool bullets were detected in the "
                "expected format ('- tool_name')"
            )

    return findings


def _fuzzy_match(key: str, lookup: dict[str, str]) -> tuple[str, str] | None:
    """Returns (matching_name, id) by approximate similarity, or None."""
    if not key or not lookup:
        return None
    matches = difflib.get_close_matches(key, lookup.keys(), n=1, cutoff=_FUZZY_CUTOFF)
    if matches:
        name = matches[0]
        return name, lookup[name]
    return None


def _match_candidate(
    key: str, lookup: dict[str, str]
) -> tuple[str | None, str | None, str]:
    """
    Resolves `key` against `lookup` (lowercase_name -> id) trying, in
    order, exact match, then substring, then fuzzy.
    Returns (resolved_id_or_None, matching_name_or_None, method), where
    method ∈ {"exact", "substring", "fuzzy", "no_match"}.
    """
    if key in lookup:
        return lookup[key], key, "exact"

    for name, rid in lookup.items():
        if key and (key in name or name in key):
            return rid, name, "substring"

    fuzzy = _fuzzy_match(key, lookup)
    if fuzzy:
        name, rid = fuzzy
        return rid, name, "fuzzy"

    return None, None, "no_match"


@dataclass
class ResolvedImportFindings:
    """
    Result of trying to translate findings.reports_to_guess /
    department_guess (free text) into real ids within a target
    organization.
    """

    resolved_reports_to_role_id: str | None = None
    suggested_department_id: str | None = None
    department_source: str | None = (
        None  # "resolved_superior" | "department_guess" | "role_name_hint"
    )
    ambiguous_candidates: list[str] = field(default_factory=list)
    unmatched_candidates: list[str] = field(default_factory=list)
    fuzzy_matches: list[tuple[str, str, str]] = field(
        default_factory=list
    )  # (candidate, matching_name, role_id)
    resolution_notes: list[str] = field(default_factory=list)


def _resolve_reports_to(
    findings: ImportFindings, spec: OrgSpec, resolved: ResolvedImportFindings
) -> None:
    if not findings.reports_to_guess:
        resolved.resolution_notes.append(
            "No 'reports to' text detected; nothing to resolve."
        )
        return

    role_lookup: dict[str, str] = {r.name.strip().lower(): r.id for r in spec.roles}
    actor_lookup: dict[str, str] = {a.id.strip().lower(): a.role for a in spec.actors}
    combined_lookup: dict[str, str] = {**role_lookup, **actor_lookup}

    raw = findings.reports_to_guess
    candidates = [
        c.strip()
        for c in _CANDIDATE_SPLIT_RE.split(raw)
        if c.strip()
        and re.search(r"[A-Za-z]", c)
        # Possessive/contraction fragments like "'Connor" from
        # "John O'Connor" are always split noise, never a real name.
        and not c.strip().startswith(("'", '"'))
    ] or [raw.strip()]

    matched_role_ids: set[str] = set()
    unmatched: list[str] = []

    for cand in candidates:
        key = cand.lower()
        role_id, matched_name, method = _match_candidate(key, combined_lookup)
        if role_id is not None:
            matched_role_ids.add(role_id)
            if method == "fuzzy":
                resolved.fuzzy_matches.append((cand, matched_name or "", role_id))
        else:
            unmatched.append(cand)

    resolved.unmatched_candidates = unmatched

    if resolved.fuzzy_matches:
        for cand, matched_name, role_id in resolved.fuzzy_matches:
            resolved.resolution_notes.append(
                f"'{cand}' doesn't match anything exactly; resolved by "
                f"fuzzy match to '{matched_name}' (role_id='{role_id}') — "
                f"verify by hand, a fuzzy match can confuse similar names "
                f"(e.g. a typo or a non-literal abbreviation)."
            )

    if len(matched_role_ids) == 1:
        role_id = next(iter(matched_role_ids))
        resolved.resolved_reports_to_role_id = role_id
        resolved.suggested_department_id = spec.role_by_id(role_id).department
        resolved.department_source = "resolved_superior"
        note = f"'{raw}' resolved unambiguously to role_id='{role_id}'."
        if unmatched:
            note += (
                f" Candidates with no match in the spec: {unmatched} "
                f"(check if they are external humans → reports_to_human, not a role)."
            )
        resolved.resolution_notes.append(note)
    elif len(matched_role_ids) > 1:
        resolved.ambiguous_candidates = sorted(matched_role_ids)
        resolved.resolution_notes.append(
            f"'{raw}' matches {len(matched_role_ids)} different roles "
            f"({sorted(matched_role_ids)}) — it is the same ambiguous "
            f"escalation pattern detected in the original Verdant Aquaponics Co-op "
            f"audit (an agent escalating to several people without an "
            f"explicit matrix). It must be resolved by hand with a single "
            f"escalation_matrix entry per condition, not left as free text "
            f"with several destinations."
        )
    else:
        resolved.resolution_notes.append(
            f"'{raw}' doesn't match any known role or actor in the target "
            f"organization; it may be an external human (use reports_to_human) "
            f"or require manual review."
        )


def _resolve_department(
    findings: ImportFindings, spec: OrgSpec, resolved: ResolvedImportFindings
) -> None:
    # Priority 1: already resolved via the superior (most reliable — the
    # real department of the resolved role, not a text inference).
    if resolved.suggested_department_id:
        return

    dept_lookup: dict[str, str] = {
        d.name.strip().lower(): d.id for d in spec.departments
    }

    # Priority 2: there is an explicit "**Department**:" detected in the text.
    if findings.department_guess:
        key = findings.department_guess.strip().lower()
        dept_id, _, method = _match_candidate(key, dept_lookup)
        if dept_id:
            resolved.suggested_department_id = dept_id
            resolved.department_source = f"department_guess ({method})"
            note = f"Department '{findings.department_guess}' resolved ({method}) to '{dept_id}'."
            if method == "fuzzy":
                note += " Approximate match — verify by hand."
            resolved.resolution_notes.append(note)
            return
        else:
            resolved.resolution_notes.append(
                f"Detected department ('{findings.department_guess}') doesn't "
                f"match any department in the target organization; pass it by "
                f"hand with --department."
            )
            return

    # Priority 3 (low confidence, declared as such): look for a department
    # name as substring inside the detected role, e.g. "Director of
    # Operations" contains "Operations".
    if findings.role_name_guess:
        role_text = findings.role_name_guess.lower()
        hits = [
            (name, did)
            for name, did in dept_lookup.items()
            if name and name in role_text
        ]
        if len(hits) == 1:
            name, dept_id = hits[0]
            resolved.suggested_department_id = dept_id
            resolved.department_source = "role_name_hint"
            resolved.resolution_notes.append(
                f"Department not detected explicitly, but the role "
                f"('{findings.role_name_guess}') mentions '{name}' — "
                f"'{dept_id}' is suggested with low confidence, review by hand."
            )
            return
        elif len(hits) > 1:
            resolved.resolution_notes.append(
                f"The role ('{findings.role_name_guess}') mentions several "
                f"possible department names ({[n for n, _ in hits]}); "
                f"ambiguous, none is suggested automatically."
            )
            return

    resolved.resolution_notes.append(
        "Could not infer the department through any path "
        "(neither resolved superior, nor detected '**Department**:', nor "
        "a match in the role name); pass it with --department."
    )


def resolve_against_org(
    findings: ImportFindings, spec: OrgSpec
) -> ResolvedImportFindings:
    """
    Tries to resolve findings.reports_to_guess / department_guess against
    the roles, actors and departments of `spec`.

    reports_to rules:
    - The text is split into candidates by commas/"o"/"y"/"or"/"and" (the
      real pattern from the Verdant Aquaponics Co-op audit: "Diego escalates to
      Marco, Board President or Tomás").
    - Each candidate is resolved by exact match → substring → fuzzy
      (difflib, for typos/non-literal abbreviations), in that order of
      confidence. Fuzzy matches are flagged separately and always with an
      explicit verification note — they are never presented with the same
      confidence as an exact match.
    - If all matching candidates point to the same role, it resolves
      unambiguously (the unmatched ones are listed separately, in case
      they are external humans). If they point to different roles, it is
      real ambiguity and is not resolved automatically.

    department rules (in order of priority and confidence):
    1. The department of the role already resolved via reports_to (most
       reliable).
    2. An explicit "**Department**:" detected in the text, resolved
       against the real departments (exact → substring → fuzzy).
    3. A department-name match inside the detected role text (low
       confidence, explicitly declared as such).
    4. Nothing — left for --department, with the reason explained.
    """
    resolved = ResolvedImportFindings()
    _resolve_reports_to(findings, spec, resolved)
    _resolve_department(findings, spec, resolved)
    return resolved


def render_org_yaml_fragment(
    findings: ImportFindings,
    role_id: str,
    department_id: str,
    access_level: str = "level-2",
    resolved: ResolvedImportFindings | None = None,
) -> str:
    """
    Returns a readable YAML fragment (not a complete org.yaml) with a
    proposed `roles[]` and `actors[]`, ready to review and paste by hand
    into the real org.yaml — never written directly because the fields
    come from a heuristic over free text, not from a spec.
    """
    lines = [
        "# --- fragment proposed by `po import-audit`, review before accepting ---",
        "roles:",
    ]
    lines.append(f"  - id: {role_id}")
    lines.append(f'    name: "{findings.role_name_guess or "<FILL_IN: role name>"}"')

    if (
        resolved
        and resolved.department_source
        and resolved.department_source != "resolved_superior"
    ):
        lines.append(
            f"    department: {department_id}  # suggested ({resolved.department_source})"
        )
    else:
        lines.append(f"    department: {department_id}")

    if resolved and resolved.resolved_reports_to_role_id:
        lines.append(
            f"    reports_to: {resolved.resolved_reports_to_role_id}  "
            f"# resolved automatically from '{findings.reports_to_guess}'"
        )
    elif resolved and resolved.ambiguous_candidates:
        lines.append(
            f"    reports_to: null  # AMBIGUOUS: '{findings.reports_to_guess}' "
            f"matches {resolved.ambiguous_candidates} — resolve by hand"
        )
    else:
        lines.append(
            f"    reports_to: null  # {findings.reports_to_guess or '<REVIEW: not detected>'}"
        )

    if resolved and resolved.unmatched_candidates:
        humans = resolved.unmatched_candidates
        note = (
            "  # REVIEW: candidate(s) with no match in the org spec — "
            "external human(s)?"
        )
        if len(humans) > 1:
            note += f" (also: {', '.join(humans[1:])})"
        lines.append(f'    reports_to_human: "{humans[0]}"{note}')

    lines.append(f"    access_level: {access_level}")
    lines.append("    functions: []  # <FILL_IN>")
    lines.append("")
    lines.append("actors:")
    lines.append(f"  - id: {findings.actor_id}")
    lines.append(f"    role: {role_id}")
    if findings.telegram_bot:
        lines.append(f'    telegram_bot: "{findings.telegram_bot}"')
    else:
        lines.append("    telegram_bot: null  # <FILL_IN: not detected>")
    if findings.tools_guess:
        tools_str = ", ".join(findings.tools_guess)
        lines.append(f"    tools: [{tools_str}]  # <REVIEW: inferred from tools.md>")
    else:
        lines.append("    tools: []  # <FILL_IN: could not be inferred>")

    return "\n".join(lines) + "\n"
