"""Update package (SPEC §13): render persona document-management scaffolding.

``pd setup`` applies, idempotently, on top of a PhantomOrg persona
installation:

  - ``kb/procedures/Documents.md`` — the document-management protocol
  - ``MEMORY.md`` — a compact pointer to the protocol
  - ``tools/documents.sh`` — a thin wrapper pinning ``--actor``

Everything written into the persona's own files (Documents.md, MEMORY.md) is
bounded by ``<!-- phantomdocs:start/end -->`` markers, so persona-authored
content outside the markers is preserved across re-runs. The wrapper is a
generated file and is replaced wholesale (it is marked as generated).
"""

from __future__ import annotations

import os
from typing import Any

START = "<!-- phantomdocs:start -->"
END = "<!-- phantomdocs:end -->"


def _bounded_block(content: str) -> str:
    return f"{START}\n{content.rstrip()}\n{END}"


def apply_bounded(path: str, content: str) -> None:
    """Write ``content`` into ``path``, bounded by the phantomdocs markers.

    Replaces an existing phantomdocs block in place (preserving persona-owned
    content before/after it) or appends the block if absent. Idempotent:
    re-running yields the same file.
    """
    block = _bounded_block(content)
    if os.path.exists(path):
        with open(path, "r", encoding="utf-8") as f:
            existing = f.read()
        if START in existing and END in existing:
            i = existing.index(START)
            j = existing.index(END) + len(END)
            head = existing[:i].rstrip("\n")
            tail = existing[j:].lstrip("\n")
            parts = [p for p in (head, block, tail) if p]
            with open(path, "w", encoding="utf-8") as f:
                f.write("\n\n".join(parts) + "\n")
            return
        with open(path, "a", encoding="utf-8") as f:
            if existing and not existing.endswith("\n"):
                f.write("\n")
            f.write(block + "\n")
    else:
        with open(path, "w", encoding="utf-8") as f:
            f.write(block + "\n")


def _inbox_of(org: dict[str, Any], actor_id: str) -> dict[str, Any] | None:
    """The ``documents.inboxes.<actor>`` entry (SPEC §13, issue #33)."""
    documents = org.get("documents") or {}
    inboxes = documents.get("inboxes") or {}
    return inboxes.get(actor_id)


def _resolved_categories_text(org: dict[str, Any], actor_id: str) -> str:
    """A human-readable line describing the actor's read scope."""
    from .access import resolved_categories

    cats = resolved_categories(org, actor_id)
    return ", ".join(cats) if cats else "(none — actor has no category grants)"


def render_documents_protocol(
    org: dict[str, Any],
    actor_id: str,
    namespace: str,
    org_pubkey: str = "",
) -> str:
    """The document-management protocol for one persona (SPEC §13)."""
    inbox = _inbox_of(org, actor_id)
    inbox_line = (
        f"- **Inbox:** `{inbox['name']}` (Drive id `{inbox['id']}`) — index by "
        f"reference with `documents.sh add --ref gdrive://{inbox['id']} ...`"
        if inbox
        else "- **Inbox:** none declared in `documents.inboxes` — the wrapper "
        "still works with `--ref file://...` / local files."
    )
    scope = _resolved_categories_text(org, actor_id)

    return f"""# Document management (PhantomDocs)

This persona manages documents with PhantomDocs (`pd`). The authoritative
access model is PhantomOrg's `org.yaml`; `pd` resolves this persona's read
scope and write owners from it (fail-closed: no rule → denied).

- **Actor:** `{actor_id}`
- **Namespace:** `{namespace}`
- **Read scope (categories):** {scope}
{inbox_line}

## Everyday usage

```bash
documents.sh add <file> --slug <slug> --folder <folder> --category <category-id>
documents.sh add --ref gdrive://<file_id> --slug <slug> --folder <folder>
documents.sh get <urn|path|slug> --cat
documents.sh search <term>
documents.sh verify
documents.sh status
```

## Rules

1. Every document is classified with a `category` id. Never reclassify by
   passing a different `--category` on `add` — reclassification is a separate
   operation.
2. A write requires read access to the category AND membership in the node's
   `owners` (role or actor id). No owners → denied.
3. Prefer `--ref` (index by reference) for objects that already live in the
   Drive inbox or a shared location, so nothing is copied twice.
4. `verify` recomputes the MAC chain and content hashes; run it after bulk
   changes.

## Scope

Generated by `pd setup` from `org.yaml`. Managed block; do not hand-edit
between the markers.
"""


def render_memory_pointer(namespace: str, actor_id: str) -> str:
    """A compact MEMORY.md pointer to the protocol (SPEC §13)."""
    return f"""## Document management

This persona manages documents with PhantomDocs (`pd`, namespace
`{namespace}`, actor `{actor_id}`). Protocol and commands:
`kb/procedures/Documents.md`. Run `documents.sh` for document operations.
"""


def render_wrapper(org_yaml_path: str, actor_id: str) -> str:
    """The ``tools/documents.sh`` wrapper pinning ``--actor`` (issue #33 stopgap).

    Once phantombot injects ``PHANTOMDOCS_ACTOR`` for the focused persona,
    the explicit ``--actor`` pin is redundant but harmless (the flag still
    wins over the environment variable per SPEC §9 precedence).
    """
    return f"""#!/usr/bin/env bash
# Generated by `pd setup` — do not edit by hand.
# Pins the actor id until phantombot provides $PHANTOMDOCS_ACTOR.
exec pd --actor {actor_id!r} --org-yaml {org_yaml_path!r} "$@"
"""


def write_wrapper(path: str, content: str) -> None:
    """Write the generated wrapper as an executable file."""
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
    try:
        os.chmod(path, 0o755)
    except OSError:
        pass
