"""Update package (SPEC §13): render persona document-management scaffolding.

``pd setup`` applies, idempotently, on top of a PhantomOrg persona
installation:

  - ``kb/procedures/Documents.md`` — the document-management protocol
  - ``MEMORY.md`` — a compact pointer to the protocol
  - ``tools/documents.sh`` — a thin wrapper pinning ``--actor``

Everything written into the persona's own files (Documents.md, MEMORY.md) is
bounded by ``<!-- phantomdocs:start/end -->`` markers, so persona-authored
content outside the markers is preserved across re-runs. The wrapper is a
generated file and is replaced wholesale (it is marked as generated).
"""

from __future__ import annotations

import os
from typing import Any

START = "<!-- phantomdocs:start -->"
END = "<!-- phantomdocs:end -->"


def _bounded_block(content: str) -> str:
    return f"{START}\n{content.rstrip()}\n{END}"


def apply_bounded(path: str, content: str) -> None:
    """Write ``content`` into ``path``, bounded by the phantomdocs markers.

    Replaces an existing phantomdocs block in place (preserving persona-owned
    content before/after it) or appends the block if absent. Idempotent:
    re-running yields the same file.
    """
    block = _bounded_block(content)
    if os.path.exists(path):
        with open(path, "r", encoding="utf-8") as f:
            existing = f.read()
        if START in existing and END in existing:
            i = existing.index(START)
            j = existing.index(END) + len(END)
            head = existing[:i].rstrip("\n")
            tail = existing[j:].lstrip("\n")
            parts = [p for p in (head, block, tail) if p]
            with open(path, "w", encoding="utf-8") as f:
                f.write("\n\n".join(parts) + "\n")
            return
        with open(path, "a", encoding="utf-8") as f:
            if existing and not existing.endswith("\n"):
                f.write("\n")
            f.write(block + "\n")
    else:
        with open(path, "w", encoding="utf-8") as f:
            f.write(block + "\n")


def _inbox_of(org: dict[str, Any], actor_id: str) -> dict[str, Any] | None:
    """The ``documents.inboxes.<actor>`` entry (SPEC §13, issue #33)."""
    documents = org.get("documents") or {}
    inboxes = documents.get("inboxes") or {}
    return inboxes.get(actor_id)


def _resolved_categories_text(org: dict[str, Any], actor_id: str) -> str:
    """A human-readable line describing the actor's read scope."""
    from .access import resolved_categories

    cats = resolved_categories(org, actor_id)
    return ", ".join(cats) if cats else "(none — actor has no category grants)"


def render_documents_protocol(
    org: dict[str, Any],
    actor_id: str,
    namespace: str,
    org_pubkey: str = "",
) -> str:
    """The document-management protocol for one persona (SPEC §13)."""
    inbox = _inbox_of(org, actor_id)
    inbox_line = (
        f"- **Inbox:** `{inbox['name']}` (Drive id `{inbox['id']}`) — index by "
        f"reference with `documents.sh add --ref gdrive://{inbox['id']} ...`"
        if inbox
        else "- **Inbox:** none declared in `documents.inboxes` — the wrapper "
        "still works with `--ref file://...` / local files."
    )
    scope = _resolved_categories_text(org, actor_id)

    return f"""# Document management (PhantomDocs)

This persona manages documents with PhantomDocs (`pd`). The authoritative
access model is PhantomOrg's `org.yaml`; `pd` resolves this persona's read
scope and write owners from it (fail-closed: no rule → denied).

- **Actor:** `{actor_id}`
- **Namespace:** `{namespace}`
- **Read scope (categories):** {scope}
{inbox_line}

## Everyday usage

```bash
documents.sh add <file> --slug <slug> --folder <folder> --category <category-id>
documents.sh add --ref gdrive://<file_id> --slug <slug> --folder <folder>
documents.sh get <urn|path|slug> --cat
documents.sh search <term>
documents.sh verify
documents.sh status
```

## Rules

1. Every document is classified with a `category` id. Never reclassify by
   passing a different `--category` on `add` — reclassification is a separate
   operation.
2. A write requires read access to the category AND membership in the node's
   `owners` (role or actor id). No owners → denied.
3. Prefer `--ref` (index by reference) for objects that already live in the
   Drive inbox or a shared location, so nothing is copied twice.
4. `verify` recomputes the MAC chain and content hashes; run it after bulk
   changes.

## Scope

Generated by `pd setup` from `org.yaml`. Managed block; do not hand-edit
between the markers.
"""


def render_memory_pointer(namespace: str, actor_id: str) -> str:
    """A compact MEMORY.md pointer to the protocol (SPEC §13)."""
    return f"""## Document management

This persona manages documents with PhantomDocs (`pd`, namespace
`{namespace}`, actor `{actor_id}`). Protocol and commands:
`kb/procedures/Documents.md`. Run `documents.sh` for document operations.
"""


# Subcommands that accept --actor / --org-yaml. Kept in sync with the Click
# options on `pd` (they are command-local options, NOT group options).
_ACTOR_COMMANDS = {"mkdir", "add", "get", "versions", "search", "tag", "acl", "setup"}
_ORG_YAML_COMMANDS = {
    "mkdir",
    "add",
    "get",
    "versions",
    "search",
    "verify",
    "tag",
    "acl",
    "setup",
    "derive-manifest",
}


def render_wrapper(org_yaml_path: str, actor_id: str) -> str:
    """The ``tools/documents.sh`` wrapper pinning ``--actor`` (issue #33).

    ``--actor`` and ``--org-yaml`` are **command-local** Click options, so
    they must be injected *after* the selected subcommand — and only for
    subcommands that accept them. The wrapper therefore reorders argv:
    ``documents.sh add foo --slug x`` becomes
    ``pd add --actor <id> --org-yaml <path> foo --slug x``, while
    ``documents.sh status`` stays ``pd status``. An operator may still pass
    ``--actor``/``--org-yaml`` explicitly (the wrapper then does not inject
    its own copy), or set ``PHANTOMDOCS_ACTOR`` for the remaining commands.

    PhantomDocs is additive and never requires phantombot to change: the
    wrapper pins the persona's actor id so no per-tool hook is needed.
    """
    actor_commands = " ".join(sorted(_ACTOR_COMMANDS))
    org_yaml_commands = " ".join(sorted(_ORG_YAML_COMMANDS))
    return f"""#!/usr/bin/env bash
# Generated by `pd setup` — do not edit by hand.
# Pins the actor id for this persona (no phantombot hook required).
set -u

ACTOR={actor_id!r}
ORG_YAML={org_yaml_path!r}

ACTOR_CMDS='{actor_commands}'
ORG_YAML_CMDS='{org_yaml_commands}'

in_list() {{
  local needle=$1 list=$2 word
  for word in $list; do
    [[ $word == "$needle" ]] && return 0
  done
  return 1
}}

has_opt() {{
  local needle=$1 a
  shift
  for a in "$@"; do
    [[ $a == "$needle" || $a == "$needle"=* ]] && return 0
  done
  return 1
}}

cmd=''
before=()
after=()
for arg in "$@"; do
  if [[ -z $cmd && $arg != -* ]]; then
    cmd=$arg
  elif [[ -z $cmd ]]; then
    before+=("$arg")
  else
    after+=("$arg")
  fi
done

args=("${{before[@]}}")
if [[ -n $cmd ]]; then
  args+=("$cmd")
  if in_list "$cmd" "$ACTOR_CMDS" && ! has_opt --actor "${{after[@]}}"; then
    args+=(--actor "$ACTOR")
  fi
  if in_list "$cmd" "$ORG_YAML_CMDS" && ! has_opt --org-yaml "${{after[@]}}"; then
    args+=(--org-yaml "$ORG_YAML")
  fi
fi
args+=("${{after[@]}}")

exec pd "${{args[@]}}"
"""


def write_wrapper(path: str, content: str) -> None:
    """Write the generated wrapper as an executable file."""
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
    try:
        os.chmod(path, 0o755)  # nosec B103 -- generated executable wrapper
    except OSError:
        pass
